{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider.fullname" . }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
data:
  {{- with .Values.secretEnvs }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}