apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oracle-price.fullname" . }}
  labels:
    {{- include "oracle-price.labels" . | nindent 4 }}
data:
  {{- with .Values.configEnvs }}
  {{- toYaml . | nindent 4 }}
  {{- end }}