apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet-api.fullname" . }}
  labels:
    {{- include "wallet-api.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_DATABASE: {{ .Values.app.dbDatabase | quote }}