{{ if .Values.secrets.enabled }}
{{- $name := include "hummingbot.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
  {{- include "hummingbot.labels" . | nindent 4 }}
type: Opaque
data:
{{ if $secret }}
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{ else }}
  PASSWORD: {{ .Values.secrets.password | b64enc | quote }}
{{- end }}
{{- end }}