apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ETHEREUM_POLLING_INTERVAL: {{ .Values.graph.ethereumPollingInterval | quote }}
  EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: {{ .Values.graph.experimentalSubgraphVersionSwitchingMode | quote }}
  ETHEREUM_BLOCK_BATCH_SIZE: {{ .Values.graph.ethereumBlockBatchSize | quote }}
  GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: {{ .Values.graph.graphEthereumMaxBlockRangeSize | quote }}
  STORE_CONNECTION_POOL_SIZE: {{ .Values.graph.storeConnectionPoolSize | quote }}
  GRAPH_LOG: {{ .Values.graph.graphLog | quote }}
  {{- if not .Values.ipfs.existingSecret }}
  ipfs: {{ .Values.graph.ipfsUrl | quote }}
  {{- end }}
  ethereum: {{ .Values.graph.ethereumNode | quote }}
  postgres_host: {{ .Values.postgresql.auth.hostname | default "graph-node-postgresql" | quote }}
  postgres_port: {{ .Values.postgresql.auth.port | default "5432" | quote }}
  postgres_user: {{ .Values.postgresql.auth.username | quote }}
  postgres_db: {{ .Values.postgresql.auth.database | quote }}
