apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "market-publisher.fullname" . }}-addresses
  labels:
    {{- include "market-publisher.labels" . | nindent 4 }}
data:
  addresses.json: |-
    {{ .Values.addresses | toJson }}