apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "market-publisher.fullname" . }}
  labels:
    {{- include "market-publisher.labels" . | nindent 4 }}
data:
  {{- with .Values.configEnvs }}
  {{- toYaml . | nindent 4 }}
  {{- end }}