apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aquarius.fullname" . }}-addresses
  labels:
    {{- include "aquarius.labels" . | nindent 4 }}
data:
  addresses.json: |-
    {{ .Values.addresses | toJson }}