apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hype-backend.fullname" . }}
  labels:
    {{- include "hype-backend.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  PROVIDER: {{ .Values.app.provider | quote }}
  WALLET_HOST: {{ .Values.app.walletHost | quote }}
  HYPE_CONTRACT_ADDRESS: {{ .Values.app.hypeContractAddress | quote }}
  ESCROW_CONTRACT_ADDRESS: {{ .Values.app.escrowContractAddress | quote }}
  ECHO_CONTRACT: {{ .Values.app.echoContractAddress | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_DATABASE: {{ .Values.app.dbDatabase | quote }}
  IPFS_HOST: {{ .Values.app.ipfsHost | quote }}
  IPFS_PORT: {{ .Values.app.ipfsPort | quote }}
  IPFS_PROTOCOL: {{ .Values.app.ipfsProtocol | quote }}
  IPFS_URL: {{ .Values.app.ipfsUrl | quote }}
  IPFS_BASE_URL: {{ .Values.app.ipfsBaseUrl | quote }}
  IPFS_USE_AUTH: {{ .Values.app.ipfsUseAuth | quote }}
  SUBGRAPH_HOST: {{ .Values.app.subgraphHost | quote }}